### ISSUE TITLE
"It's not really free."

### ISSUE THREAD

**Issue by E-toolmaster** [Remove-Background-ai/rembg.js#2] opened 2023-07-24 09:23 UTC
hi i'm read: "this is THE ONLY FREE library available for personal usage from API"
but when i called request with API KEY. it's reponse : 429 error..so ..it's no free :)

**Comment by mtrabelsi** [comment] 2023-07-24 14:33
Hi thanks for your report,

I would close the issue as this is not a bug itself.

However to answer this:


IF you sign up you will get has 60 credits per month, which is almost 16$ credits renewable every month for FREE.
None of other enterprise grade background removal give you free usage through the API. only through the app but it is also limited through the app.

We need to rate limit for free users, running a single inference cost almost 1 cent, we need to manage server costs for now.
if you want more you can sign up for premium (which is extremally cheap comparing to other tools)

**Closed as completed by mtrabelsi** 2023-07-24 14:33 UTC
